spring.application.name=SpringSecurity
#spring.security.user.name=kiruba
#spring.security.user.password=1234

spring.datasource.url=jdbc:postgresql://localhost:5432/securitydb
spring.datasource.username=postgres
spring.datasource.password=1234